export const metadata = {
  title: 'Frontend Mentor | Todo app',
  description: 'Generated by Next.js',
  image: '/favicon-32*32.png'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">    
      <body>{children}</body>
    </html> 
  )
}
