export const metadata = {
  title: 'Frontend Mentor | Todo app',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon-32x32.png" sizes="any" />  
      </head>    
      <body>{children}</body>
    </html> 
  )
}
